language: node_js
node_js:
- 10.6.0
install:
- npm install
cache:
  directories:
  - node_modules
script:
- npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: MR7G4eGV/vf7ce/duzi5oFldVBgJOSDeHxrrrOFfRzzzup+sTZIrL3wCvMPCERyAknJFEubZ9/hbX5xNZSMxWXhVauv9XpyvGnyi0X9WpY6FYbPdhEuEYAssCQ5csAvPvMfPsuztSaGvvplMF1DxqND4Jpv9l2JD1cb5WOE6gxjORjL0eQBCuwCnGgt0tqDm7FPsFvH5PJFxnCIVrz/dEymuAYdJho+6umc4QjeYEDt5D8IdmlCZZwjSotJnR9TcGHwlrFIL5+hLunuabFymxxWNmI7uGQWJDWACTbEFuE22M6hACnBF01lXWylvyCobd3F4oOFj/4L3Xj95T1QD0Eh7cWE6i887o/XMDxpxW6AqeG1GFy2hW2D6yN1EQtnfo/huAUs5tTr47hK7Cqo8BARbNrfoRVGDfImwxWox5lA80eeGSbDGRN/FSBy7xGErQM/lPKJ434bG5qiftqO3PnYuaqprEI56Ftze9vo3kivyER2c0AbnvTaMuEds2WGUwcm9LH7Du7zSIs7FwP9XpdiJDLoCt3qpjQYP8XOL9pB9hmyP5wcSOmX5Rrw7ATXAM4SRLav+cwCfnZ98s2il+pvnKvFEcvW/w87PbRSCJRo6IkT/ZIixdvvCeFrH9UWLs8ct7oSa7Dn5AmEmfJWYXqqV7WE3WQ9jovE+0xBCtMM=
