#!/bin/sh
mkdir -p dist
browserify \
  --delay=100 \
  --verbose \
  --transform [ babelify ] \
  --outfile dist/app.js \
  --debug \
  src/app.js

uglifyjs dist/app.js \
  --mangle \
  --compress \
  --output dist/app.js
