#!/bin/sh
rm -rf dist
mkdir -p dist

browserify \
  --delay=100 \
  --verbose \
  --transform [ babelify ] \
  --outfile dist/app.js \
  --debug \
  src/app.js

uglifyjs dist/app.js \
  --mangle \
  --compress \
  --output dist/app.min.js

rm dist/app.js

postcss src/style/style.css > dist/style.min.css

cp -R assets dist

cp CNAME dist

HTML_INPUT='index.hbs' \
HTML_OUTPUT='dist/index.html' \
CSS_PATH='style.min.css' \
JS_PATH='app.min.js' \
  node tasks/helpers/handlebars.js
